services:
  prometheus:
    image: prom/prometheus:v2.27.1
    restart: unless-stopped
    volumes:
    - ./prometheus/:/etc/prometheus/:ro
    - prometheus_data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - 9090:9090
    links:
    - ping:ping
    # - speedtest:speedtest
    networks:
    - backend

  grafana:
    image: grafana/grafana:7.5.7
    restart: always
    volumes:
    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
    - prometheus
    ports:
    - 3030:3000
    environment:
      GF_INSTALL_PLUGINS: flant-statusmap-panel
      GF_SECURITY_ADMIN_PASSWORD: wonka
      GF_USERS_ALLOW_SIGN_UP: 'false'
    networks:
    - backend
    - frontend

  ping:
    tty: true
    stdin_open: true
    expose:
    - 9115
    ports:
    - 9115:9115
    image: prom/blackbox-exporter:v0.19.0
    restart: always
    volumes:
    - ./blackbox/config:/config
    networks:
    - backend

  # speedtest:
  #   tty: true
  #   stdin_open: true
  #   expose:
  #   - 9798
  #   ports:
  #   - 9798:9798
  #   image: miguelndecarvalho/speedtest-exporter
  #   restart: always
  #   networks:
  #   - backend

  # nodeexp:
  #   image: prom/node-exporter:v1.1.2
  #   privileged: true
  #   volumes:
  #   - /proc:/host/proc:ro
  #   - /sys:/host/sys:ro
  #   - /:/rootfs:ro
  #   ports:
  #   - 9100:9100
  #   restart: always
  #   command:
  #   - '--path.procfs=/host/proc'
  #   - '--path.sysfs=/host/sys'
  #   - --collector.filesystem.ignored-mount-points
  #   - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  #   networks:
  #   - backend

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  frontend:
  backend:
