apiVersion: 1

deleteDatasources:
- name: prometheus
  orgId: 1

datasources:
- name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  # database:
  # user:
  # password:
  basicAuth: true
  basicAuthUser: admin
  # withCredentials:
  isDefault: true
  jsonData:
    graphiteVersion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
  secureJsonData:
    basicAuthPassword: foobar
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  # allow users to edit datasources from the UI.
  editable: true
